# Generated by Django 4.2.7 on 2024-02-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='Nom',
            field=models.CharField(default='VotreValeurParDefaut', max_length=65),
        ),
        migrations.AddField(
            model_name='user',
            name='Prenom',
            field=models.CharField(default='VotreValeurParDefaut', max_length=65),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
