# Generated by Django 4.2.7 on 2024-02-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvent', '0002_remove_user_name_user_nom_user_prenom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Nom',
            field=models.CharField(default='', max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Prenom',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
