# Generated by Django 4.2.7 on 2024-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvent', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='mail',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
