# Generated by Django 4.2.7 on 2024-03-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvent', '0005_event_utilisateur_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lieu',
            field=models.CharField(default='', max_length=100),
        ),
    ]
