# Generated by Django 4.2.7 on 2024-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvent', '0007_alter_event_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lieu',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
