# Generated by Django 4.2.7 on 2024-03-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEvent', '0008_alter_event_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
